# Generated by Django 3.2.3 on 2021-10-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='email_address',
        ),
    ]
