# Generated by Django 3.2.7 on 2021-10-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
