# Generated by Django 3.2.7 on 2021-09-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poke',
        ),
        migrations.DeleteModel(
            name='Poke2',
        ),
    ]
